#weight_init: kaiming_normal
#score_init: None
dataset: WTH

weight_seed: 2
score_seed: 0
gpu: 0
batch_size: 128

model_type: 'Sparse'
attention: 'Dense'

epochs: 100
weight_file: sparse_ts_wth

layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5

has_src_mask: False


dmodel: 100
forecast: True
save_scores: False
layer_norm: True
batch_norm: False
save_graphs: False

pos_enc: 'Standard'
lr: .001
scheduler: True
es_epochs: 5


forecasting_steps: 1
window_size: 200